name: "Cross Organization Issue Linkage"
description: "Syncs status of this repo's issues with that of issues in repos in
any external org"
author: "Sarina Canelake"
inputs:
  API_TOKEN:
    description: "Token that allows access to the GitHub API"
    required: true
  ORGREPO:
    description: "the org/repo of this repository; use ${{ github.repository }}"
    required: true
outputs:
  orgRepo:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
