name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest

        # Put your action repo here
        uses: sarina/cross-organization-issue-linkage@master
        with:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          ORGREPO: ${{ GITHUB_ACTION_REPOSITORY }}

      - name: Check outputs
        run: |
          test "${{ steps.selftest.outputs.linkedIssueInfo }}" =~ .*openedx.*"
